# Dataset Configuration
dataset:
  name: "adult-census-income"
  source: "scikit-learn/adult-census-income"
  split: "train"
  platform: "huggingface"
  protected_attributes:
    - "sex"
    - "race"
  target_column: "income"
  sampling:
    enabled: false
    n_samples: 500 # Number of samples to use for quick experiments
    random_seed: 42

# Post-processing Configuration
post_processing:
  binary_mapping:
    favorable_outcome: ">50K"
    unfavorable_outcome: "<=50K"

  attribute_groups:
    sex:
      privileged: ["Male"]
      unprivileged: ["Female"]
    race:
      privileged: ["White"]
      unprivileged: ["Black", "Other"]

# Model Configuration
model:
  # Model task type for Fairness Compass routing
  model_task: "binary_classification" # Options: binary_classification, multiclass_classification, regression, generation, ranking
  label_behavior: "binary" # Options: binary, categorical, continuous

  # Hugging Face model configuration
  huggingface:
    enabled: true
    model_id: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
    device: "cuda" # or "cpu" for CPU-only inference
    max_new_tokens: 50
    temperature: 0.7
    top_p: 0.9
    system_prompt: "You are a strict classifier. You must answer with exactly one of these two strings: '>50K' or '<=50K'. No explanation. No formatting."

# Prompting Configuration
prompting:
  formatter: "tinyllama-chat"         # or "openai-chat-json"
  system_prompt: "You are a strict classifier. You must answer with exactly one of these two strings: '>50K' or '<=50K'. No explanation. No formatting." # falls back to formatter default if null
  instruction: "Given the following demographic information about a person:"   # short, reusable task intent
  assistant_preamble: "The predicted income is "         # only used by some formatters

# Metrics Configuration
metrics:
  # Fairness metrics for evaluation
  fairness:
    enabled: true
    metrics:
      - "demographic_parity"
      - "equalized_odds"
      - "predictive_parity"

  # Performance metrics
  performance:
    enabled: false
    metrics:
      - "accuracy"
      - "precision"

artifacts:
  inference_results_path: "artifacts/cleaned_inference_results.csv"
  postprocessed_results_path: "artifacts/postprocessed_results.csv"
